### ISSUE TITLE
Generator does not provide dev build out of the box

### ISSUE THREAD

**Issue by stefcameron** [lensapp/generator-lens-ext#28]
Making a new issue from https://github.com/lensapp/lens/issues/1215#issuecomment-806202335 on the generator repo.

This is what it outputs today (I just installed it and ran it) for the `Webpack.config.js` file:

```javascript
/* eslint @typescript-eslint/no-var-requires: "off" */

const path = require("path");

module.exports = [
  {
    entry: "./main.ts",
    context: __dirname,
    target: "electron-main",
    mode: "production",
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          use: "ts-loader",
          exclude: /node_modules/,
        },
      ],
    },
    externals: [
      {
        "@k8slens/extensions": "var global.LensExtensions",
        "mobx": "var global.Mobx",
        "react": "var global.React"
      }
    ],
    resolve: {
      extensions: [".tsx", ".ts", ".js"],
    },
    output: {
      libraryTarget: "commonjs2",
      filename: "main.js",
      path: path.resolve(__dirname, "dist"),
    },
  },
  {
    entry: "./renderer.tsx",
    context: __dirname,
    target: "electron-renderer",
    mode: "production",
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          use: "ts-loader",
          exclude: /node_modules/,
        },
      ],
    },
    externals: [
      {
        "@k8slens/extensions": "var global.LensExtensions",
        "react": "var global.React",
        "mobx": "var global.Mobx"
      }
    ],
    resolve: {
      extensions: [".tsx", ".ts", ".js"],
    },
    output: {
      libraryTarget: "commonjs2",
      globalObject: "this",
      filename: "renderer.js",
      path: path.resolve(__dirname, "dist"),
    },
    node: {
      __dirname: false,
      __filename: false
    }
  },
];
```

There are only __production__ build configurations in there. So right out of the box, there are no dev tools used, all the code is minified, no source maps. In other words, no debugging (or at least, no _sane_ debugging with breakpoints and code you can read).

I _think_ all you would need to add is this to your generator:

```
    // in BOTH main and renderer entry configs, REPLACE this:
    mode: "production",

    // with this:
    mode: process.env.NODE_ENV || 'production',
    devtool: process.env.NODE_ENV !== 'production' ? 'eval-source-map' : undefined,
```

Then you can run `NODE_ENV=development yarn start` to start a watch on a development build with source maps and all the things you need to start debugging in DevTools right away.

Actually, you should just change the generated package.json's `start` script to be this and make it even easier on your extension developers:

`start: "NODE_ENV=development webpack --watch"`

**Comment by chenhunghan** [comment]
@stefcameron Thanks, I added items you suggested to the webpack.config.js in this PR https://github.com/lensapp/generator-lens-ext/pull/30
